id = "logstash"
name = "Logstash"
version = "0.0.2"
schema_version = 1
authors = ["Agani Daniel Strong <adhueywilan@gmail.com>"]
description = "Logstash pipeline config file syntax highlighting support"
repository = "https://github.com/StrongTheDev/logstash-for-zed"

[grammars.logstash]
repository = "https://github.com/StrongTheDev/tree-sitter-logstash"
commit = "e2964e15f2dc19322636f5920e3bd6d28dfae415"
